version: "3.3"
services:
  nucleotide:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db/app

    networks:
      - nucleotide
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nucleotide

volumes:
  postgres-data:

networks:
  nucleotide:
    driver: bridge
